### ISSUE TITLE
Remove Precompiled iOS Binary

### ISSUE THREAD

**Issue by wrobins** [wrobins/cordova-plugin-msal#11]
Make the iOS MSAL framework pull from cocoapods or carthage.

**Comment by hugoplatell** [comment]
While testing and releasing our app, we found multiple issues with the precompiled iOS binary. It blocks running on iOS 12, the app crashes directly after startup. Furthermore, you're not allowed to run your project in an iOS simulator...

After some investigation, I removed the precompiled library from the plugin and pulled the library directly from cocoapods. This solved for us the above mentioned problems.
I opened a PR #25 with my code, it is not fully tested. I only tested our implementation of B2C login.

**Comment by wrobins** [comment]
Thanks for fixing this! So far it doesn't seem like there are any immediate issues with the new iOS implementation so I'll close this. Thanks!
