### ISSUE TITLE
Using Client_ID for different szenarios (test, staging, prod)

### ISSUE THREAD

**Issue by imamdev** [wrobins/cordova-plugin-msal#19]
Hi,
thanks for your work. 

In your plugin the CLIENT_ID is mandatory. Do you know a best practice to change this on runtime of Xcode-Build without removing and adding the plugin everytime with new ID? 
Because I currently try to build a CI project with using schemes in Xcode, but didn't really know how to change this parameter when using & building with this plugin with less effort. So I will end up in using two projects.

**Comment by wrobins** [comment]
Hello!
I'm not super familiar with Xcode development, so I apologize if I'm not as helpful here, but I'll try to help figure out how to do this.

Are you using any framework on top of Cordova, or is this a vanilla Cordova app that you're building?

Also, is this a project for iOS-only for both platforms?

**Comment by imamdev** [comment]
Hi, sorry for the late reply. I now doing dirty tricks with hooks and now it's working. So you can close this topic. Thanks!
