### ISSUE TITLE
Sign in shows null

### ISSUE THREAD

**Issue by collab-appsdev** [wrobins/cordova-plugin-msal#20]
on signing in, on the username field it shows "null"

![image](https://user-images.githubusercontent.com/49704178/81803798-c09f3800-954a-11ea-88e3-23dd50fb29ac.png)

also noticed that on the url for signing in there is a querystring "&login_hint=null" are we missing something in the configuration so that null will not appear?

**Comment by wrobins** [comment]
Hello!

I just released v2.1.1 of the plugin today, which should fix the issue you're experiencing. Let me know if it works for you after you update.

Cheers,

**Comment by collab-appsdev** [comment]
Thank you!
