### ISSUE TITLE
Please add support for windows

### ISSUE THREAD

**Issue by tboudri** [wrobins/cordova-plugin-msal#38]
Please add support for windows

**Comment by wrobins** [comment]
Hello and thanks for your feedback!

 This is planned for v3 of this plugin. I apologize for the slow pace of development these last two months but my day job has been pretty crazy and I've had to devote a lot of hours to it. But windows (and browser/javascript) support will be here soon.

**Comment by NaveenK15** [comment]
@wrobins  any update on the same? has the windows support been added yet?

**Comment by wrobins** [comment]
Unfortunately Windows support has been dropped from Cordova so this feature can no longer be supported.
