### ISSUE TITLE
brokerRedirectUri

### ISSUE THREAD

**Issue by jeffortdev** [wrobins/cordova-plugin-msal#52]
Hi, I set brokerRedirectUri to true, but nothing happened, the success nor fail callbacks did not trigger. if it is set to false, everything works fine. 

I installed the plugin as indicated.

Here are my options
`            authorities: [
              {
                type: 'AAD',
                audience: 'AzureADMyOrg',
                authorityUrl: '',
                cloudInstance: 'MSALAzurePublicCloudInstance',                
                default: true                
              }
            ],
            prompt: 'SELECT_ACCOUNT',
            authorizationUserAgent: 'WEBVIEW',
            accountMode: 'SINGLE',
            brokerRedirectUri: true,
            scopes: [
              'openid',
              'profile'
            ]`

I had set up my application on Azure portal and installed MSAuthenticator on my Android device as well.

**Comment by jeffortdev** [comment]
Closing this, turns out setting brokerRedirectUri wont work on debug and app should be wrapped by Intune wrapper.

**Comment by marutifh** [comment]
Hi @jeffortdev Can you please help me in understand how to wrap app by Intune wrapper?

**Comment by jeffortdev** [comment]
> Hi @jeffortdev Can you please help me in understand how to wrap app by Intune wrapper?

sorry for late reply, you can checkout the wrapper here https://github.com/msintuneappsdk/intune-app-wrapping-tool-ios then have documentation there explaining that
