### ISSUE TITLE
Dynamic Tenant ID

### ISSUE THREAD

**Issue by bolivir** [wrobins/cordova-plugin-msal#55]
Is there any to use an dynamic tenant ID? As far as i have seen in the code the tenant id will always be from the package.json config and cannot be set on init.

The problem: 
Our app gets used by different companies, those can enable azure login where they provide the tenant id. So we dont know the tenant id before and therefore we need to set it in the code behind.

I modified the MsalPlugin to check for an tenant id in the authorities and use that if specified otherwise use the config tenant id (Which in my case would be common because its not specified).

If you see any added value in this feature, let me know and i will open an PR for it.

**Comment by sebo-o** [comment]
I would very well be interested as I need a dynamic tenant ID and client ID. Please open a PR and share your code. Thank you!

**Comment by sagcalelisha** [comment]
Any news regarding this? I have a deadline on Monday. haha! =P Thanks!

**Comment by Jetro223** [comment]
I have the same scenario - a PR would be great.

**Comment by Aston13** [comment]
I also have the same issue

**Comment by ronakpatel17** [comment]
@bolivir I also have the same scenario. Can you please add a PR or provide changes done by you for this. Thank you in advance!

**Comment by swathi2378** [comment]
@bolivir I have the same scenario. Could you please provide the changes need to implement
