### ISSUE TITLE
How to specify the reply URL?

### ISSUE THREAD

**Issue by laughinglion** [wrobins/cordova-plugin-msal#58]
Good day,
The reply URL specified in the request does not match the reply URLs configured for the application: 'xxxxx'
How do I supply it or what do I set in the Azure portal?

**Comment by poulerik-dk** [comment]
If its android, ensure that you have configured your key-hash properly, add it as android and use your package name + your hash

**Comment by laughinglion** [comment]
Thank you for response and a great plugin, I have configured it correctly now and all is working.
