### ISSUE TITLE
Application is not configured as a multi-tenant application

### ISSUE THREAD

**Issue by wan-liyang** [wrobins/cordova-plugin-msal#78]
Hi,
when i try the Demo in outsystems application, and integrate with Azure (supported account types: Single tenant)
then encounter below error. if I change supported account types to Multitenant, then it work.

how can i make it work for Single tenant also?
I have tried
e.g. 

1. pass AuthorityUrl: https://login.microsoftonline.com/[tenant-id] to MSALInit
2. change AccountMode to Single / Multiple
3. change MSALAuthority.Audience
4. change Entities.AuthorityType.B2C / Entities.AuthorityType.AAD
5. ....

```
AADSTS50194: Application is not configured as a multi-tenant application. 
Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. 
Use a tenant-specific endpoint or configure the application to be multi-tenant.
```

**Comment by wan-liyang** [comment]
Solved my case

**Comment by ryandegruyter** [comment]
@wanliyang9012 how did you resolve your issue?

**Comment by wan-liyang** [comment]
@ryandegruyter , i manual define the MSALAuthority object and pass in MSALInit for `Authorities` input parameter

```
MSALAuthority.Type = Entities.AuthorityType.AAD
MSALAuthority.Audience = Entities.AuthorityAudience.AzureADMyOrg
MSALAuthority.CloudInstance = Entities.AuthorityCloudInstance.MSALAzurePublicCloudInstance
MSALAuthority.Default = True
```

**Comment by ryandegruyter** [comment]
Thank you
